### PR TITLE
Allow duplicated actions to be included in results

### PR DESCRIPTION
**Pull request by rrennick**
It's possible for 2 instances of the same action to be scheduled at the same time. The API controller was only returning one copy of those actions. I found this due to testing https://github.com/woocommerce/action-scheduler/pull/399.

While fixing this issue I noticed a React warning for a currency prop on the `ReportFilters` component. The second commit fixes that warning.

### CODE REVIEW

**Comment by rrennick** [comment]
@menakas Can you check this PR to see if it addresses thee pagination issue we discussed?

**Comment by menakas** [comment]
@rrennick 
Bringing the Slack question over here:

I see a blank screen on this branch. (‘_currency.default is not a constructor’ is the error on the console). On master, I get about 10 rows of pending actions. Am I missing something?

**Comment by rrennick** [comment]
> Am I missing something?

Have you `git pull` then `npm run start` in both this & WCA? If you have then try `npm run clean` before the `npm run start`.

**Comment by menakas** [comment]
@rrennick 
Thanks. I tested this on a clean installation so that whatever I was doing with WCSA wouldn't interfere with it and I find that it works perfect. 👍 Yes the pagination is fine.

**Comment by rrennick** [comment]
@menakas Awesome, thanks for the testing/review 💯

**Pull request merged**
